[project]
name = "formats-echanges-donnees-biologie"
version = "0.1.0"
description = "Formats et échanges de données en biologie"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter-book>=1.0.3",
]
